name: qod-register

artifactStorePath: .forge-ci/artifact-store.yaml

repos:
  - name: qod-register
    url: git@github.com:alexandremahdhaoui/qod-register.git
    ref: main

managers:
  - alias: local
    engine: "forge://github.com/alexandremahdhaoui/forge-ci/cmd/ci-manager-local"
    spec:
      statePath: .forge-ci/manager-local.json

engines:
  - alias: here
    type: compute
    engine: "forge://github.com/alexandremahdhaoui/forge-ci/cmd/ci-compute-local"
    manager: local

  - alias: pipeline-state
    type: state
    engine: "forge://github.com/alexandremahdhaoui/forge-ci/cmd/ci-state-git"
    manager: local
    spec:
      path: qod-state

  - alias: on-change
    type: trigger
    engine: "forge://github.com/alexandremahdhaoui/forge-ci/cmd/ci-trigger-watch"
    manager: local
    spec:
      watch: ["qod-register"]

  - alias: all-pass
    type: promotion
    engine: "forge://github.com/alexandremahdhaoui/forge-ci/cmd/ci-promotion-all"
    manager: local

state: pipeline-state
triggers: [on-change]

targets:
  - alias: process
    forge: test run process
    in: [qod-register]

  - alias: evaluate
    forge: test run evaluate
    in: [qod-register]

  - alias: canary
    forge: test run canary
    in: [qod-register]

stages:
  - name: process
    promotion: all-pass
    substages:
      - name: default
        engine: here
        manager: local
        targets: [process]

  - name: evaluate
    promotion: all-pass
    substages:
      - name: default
        engine: here
        manager: local
        targets: [evaluate]

  - name: canary
    mint: true
    promotion: all-pass
    substages:
      - name: default
        engine: here
        manager: local
        targets: [canary]
